# -*- coding: utf-8 -*-
"""
V2.0b English options, hand-transcribed from rendered exam pages
(2026年6月英语六级真题3套全.pdf set1 p1-3 / set2 p9-11).
Transcriber: model visual reading; status: candidate, pending human recheck.
Q1-4 of each set live in the pilot candidate files and are not duplicated here.
"""

SET1_OPTIONS_EN = {
    5: ["Decide how to divide up the presentation tasks.",
        "Investigate the available background research.",
        "Complete the project design together.",
        "Find a suitable topic for their article."],
    6: ["He wants to devote his time to other portions.",
        "He believes the woman is better able to handle it.",
        "He claims to have done most of the work already.",
        "He finds the woman more meticulous about details."],
    7: ["Questioning.", "Complaining.", "Arguing.", "Worrying."],
    8: ["To avoid sounding monotonous to the listeners.",
        "To make the division of labor more reasonable.",
        "To keep himself from being overburdened.",
        "To bring their capabilities fully into play."],
    9: ["Alter others' perceptions of the wearer.",
        "Win others' admiration for the wearer.",
        "Enhance the wearer's confidence.",
        "Change the wearer's appearance."],
    10: ["As being a greater threat.",
         "As being of higher prestige.",
         "As being more dominant.",
         "As being more attractive."],
    11: ["It might influence her way of introducing herself.",
         "It might impact her dressing style for the occasion.",
         "It might affect her decision on applying cosmetics.",
         "It might sway her view on the interviewers' questions."],
    12: ["Those involving no self-recognition.",
         "Those forcing us to clench our teeth.",
         "Those resisting various temptations.",
         "Those requiring no willpower at all."],
    13: ["Regulating one's actions for the sake of good health.",
         "Controlling one's actions with a motivating thought.",
         "Using practical examples to guide one's behavior.",
         "Denying oneself any comfort to prevent diseases."],
    14: ["It equips us with an expert skill.",
         "It exerts an enduring force on us.",
         "It leads to a burning goal.",
         "It begins with a bright idea."],
    15: ["Any cherished goal.", "Any positive mindset.",
         "Any personal instinct.", "Any valued role model."],
    16: ["It has long been criticized as unclear.",
         "It has long been ignored by the public.",
         "It has caused much panic among women.",
         "It has resulted in different understandings."],
    17: ["It warned consumers not to eat fish from the Gulf of Mexico.",
         "It called on expectant mothers to pay attention to food safety.",
         "It issued an update to the advice on seafood consumption.",
         "It listed more than sixty species of fish as \"choices to avoid\"."],
    18: ["The impact of the FDA's analysis.",
         "Multiple factors including mercury.",
         "Critics' conclusions.",
         "The prices of seafood."],
    19: ["They will suffer a breakdown soon.",
         "They will be losing both joy and life.",
         "They will be putting themselves and family at risk.",
         "They will make things worse for people around them."],
    20: ["Spend 14 days for vacation every year.",
         "Aim for three separate vacations yearly.",
         "Space out their vacations evenly instead of taking one long vacation.",
         "Use all their days off for a long summer break to achieve full-on calm."],
    21: ["Expecting to have more vacations in a year will boost one's work efficiency.",
         "Anticipating more vacations would reduce one's feelings of despair at work.",
         "Taking more than three vacations yearly would prolong one's excitement.",
         "Planning multiple breaks throughout the year will add to one's happiness."],
    22: ["Surveying when drivers are caught in the heat of arguments.",
         "Designing devices to prevent drivers from being distracted.",
         "Testing models for monitoring drivers easily getting tired.",
         "Developing sensor-based systems for autonomous vehicles."],
    23: ["Make sure the autonomous vehicle operates in the simplest manner.",
         "Ensure the transition from the driver to the vehicle is safely made.",
         "Alleviate the driver's pressure as much as possible.",
         "Record the driver's state as accurately as possible."],
    24: ["Driver fatigue.", "Dreadful traffic.", "Drunk driving.", "Driving time."],
    25: ["There has been a strong debate on the feasibility of Level 3 cars.",
         "There have been few remarkable advances in auto technology.",
         "There has been a rise in attention-grabbing accidents recently.",
         "There have been few feasible ways to shift public sentiment."],
}

SET2_OPTIONS_EN = {
    5: ["They often share each other's experiences.",
        "They enjoy interacting with patients.",
        "They always do things tricky.",
        "They are both pharmacists."],
    6: ["The doctor ended up admitting his mistake.",
        "The patient consulted another doctor.",
        "The patient actually took her advice.",
        "The doctor double-checked with her."],
    7: ["A proposal for applying flu shots more effectively.",
        "A new medication therapy management program.",
        "A novel strategy to persuade stubborn patients.",
        "A therapy for patients with similar conditions."],
    8: ["Inability to send text messages.",
        "Distrust in pharmaceutical experts.",
        "Medication non-adherence.",
        "Need for constant reminding."],
    9: ["Accomplish their goals.", "View things positively.",
        "Overstate their importance.", "Dominate job interviews."],
    10: ["It reflects a strong sense of obligation to others.",
         "It signifies a universal model of motivation.",
         "It may differ in various cultures.",
         "It may have been underestimated."],
    11: ["It was under-investigated.", "It was more predictable.",
         "It was taken for granted.", "It was more subtle."],
    12: ["It is any incidental happening in plants and animals or ice crystals.",
         "It is any basic physical or chemical work in designing substances.",
         "It is any symmetrical and colorful stripes or spots on organisms.",
         "It is any regularly repeated arrangement of shapes or colors."],
    13: ["Materials undergoing certain processes.",
         "Materials exposed to various natural forces.",
         "Materials impacted by any change of molecules.",
         "Materials going through extremely radical transformations."],
    14: ["The beauty of molecular clustering.",
         "The way for appreciating patterns.",
         "The creation of patterns.",
         "The factors affecting clusters."],
    15: ["A pattern by accident.", "Patterns for specific purposes.",
         "Patterns with random imperfections.",
         "A pattern with artificial intervention."],
    16: ["Eliminating all the old habits at once.",
         "Making a permanent lifestyle change.",
         "Realizing all the life goals one has set.",
         "Improving multiple areas of one's life."],
    17: ["They were more likely to implement a particular behavior.",
         "They were more likely to make plans for their future.",
         "They tended to be committed to a single goal.",
         "They tended to focus on one thing at a time."],
    18: ["The ability to make the process automatic.",
         "A practical timetable for implementation.",
         "A lot of conscious effort to remember to do it.",
         "Concentration on the benefits it will provide."],
    19: ["It resembles that of Earth in many inconceivable ways.",
         "It has a haze much thicker than previously believed.",
         "It is 333.4 \u00b0F cooler than earlier estimates.",
         "It is far beyond any quick measurements."],
    20: ["The accumulation of solid particles in the air.",
         "The distribution of gases in its atmosphere.",
         "The clouds of particles reflecting sun rays.",
         "The aggravated effects of climate change."],
    21: ["If spectrums of light can be better detected by telescope.",
         "If Pluto's hazy atmosphere can be more easily observed.",
         "If Pluto's hazy atmosphere scatters strong sunlight.",
         "If the light from the telescope confirms their idea."],
    22: ["Parents can play a decisive role in cultivating their children's musical talent.",
         "Children are embarrassed by parents' failure to appreciate their music.",
         "Parents can mould their 8- to 10-year-old children's music taste.",
         "Children aged 8 to 10 are old enough to produce poetic lyrics."],
    23: ["They start to show their own musical preference.",
         "They tend to be more influenced by their peers.",
         "They tend to gravitate away from their homes.",
         "They are more open to new genres of music."],
    24: ["Enabling children to be receptive to music experts' suggestions.",
         "Helping children develop the ability to manage their emotions.",
         "Familiarising children with different schools of music.",
         "Introducing children to a variety of musical styles."],
    25: ["By enhancing children's appreciation of their music.",
         "By pushing their music hard enough upon children.",
         "By attending their concerts and live music events with children.",
         "By introducing their music to children as early as possible."],
}

# page provenance within 2026年6月英语六级真题3套全.pdf
SET1_PAGE = {**{n: 1 for n in range(1, 7)}, **{n: 2 for n in range(7, 16)}, **{n: 3 for n in range(16, 26)}}
SET2_PAGE = {**{n: 9 for n in range(1, 9)}, **{n: 10 for n in range(9, 22)}, **{n: 11 for n in range(22, 26)}}

# official quick-answer table (真题3套全.pdf p23)
KEY_TABLE = {
    "set1": list("BCADACBAADCDBDAACBBCDDBAC".replace("ACBBCDDBAC", "ACBBCDDBAC")),
    "set2": list("AABDDCBCACDDACABACBBDCBDC"),
}
KEY_TABLE["set1"] = ['B','C','A','D','A','C','B','A','A','D','C','D','B','D','A','A','C','B','B','C','D','D','B','A','C']
KEY_TABLE["set2"] = ['A','A','B','D','D','C','B','C','A','C','D','D','A','C','A','B','A','C','B','B','D','C','B','D','C']
